### ISSUE TITLE
Rasa data validation should accept arguments

### ISSUE THREAD

**Issue by amardeep2006** [RasaHQ/rasa-train-test-gha#12]
Data validation should accept optional arguments.
Example : we wish to pass command line argument --fail-on-warning

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
