### ISSUE TITLE
Exception in cross_validation_results.py

### ISSUE THREAD

**Issue by amardeep2006** [RasaHQ/rasa-train-test-gha#14]
I am facing following error while running cross validation .

`Traceback (most recent call last):
  File "/home/runner/work/_actions/RasaHQ/rasa-train-test-gha/main/scripts/cross_validation_results.py", line 71, in <module>
    entities = entity_table()
  File "/home/runner/work/_actions/RasaHQ/rasa-train-test-gha/main/scripts/cross_validation_results.py", line 54, in entity_table
    classes = list(data.keys())
UnboundLocalError: local variable 'data' referenced before assignment
Error: Process completed with exit code 1.`

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by hsm207** [comment]
Could you please:

1. Share with us the parameters you passed to this action that led to the error?
2. Run the cross validation locally using the same parameters you passed to the action and share with us the `DIETClassifier_report.json` file?

**Comment by amardeep2006** [comment]
I did not face this issue once I added one dummy entity and few examples in training data.
