### ISSUE TITLE
Assumed working directory as /app?

### ISSUE THREAD

**Issue by bml1g12** [RasaHQ/rasa-train-test-gha#17]
Is it correct that this repository implicitly assumes that your docker image has a working directory of /app?  

I am aware I can set the path to the rasa folder via `workspace` - but it still seems to assume that when we start the train/validate/test commands, this code will be located in /app https://github.com/RasaHQ/rasa-train-test-gha/blob/63f15568983d817ffa5487bddbffa3a1d64cd126/action.yml#L168

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by HotThoughts** [comment]
The action mounts `workspace` to `/app` because all Rasa docker image assumes `/app` as the default working directory. You can set 

See: https://github.com/RasaHQ/rasa/blob/main/docker/Dockerfile.full#L52

**Comment by bml1g12** [comment]
Thanks for your comment. It took me a while to realise that this was the issue when making a custom image. 

I think a nice improvement here would just be to just add a step which asserts that `/app` is the entrypoint, or if that's ugly, maybe just documenting in the README that this Action requires your entrpoint to be `/app`

:bow:
